### ISSUE TITLE
View Post Details-1

### ISSUE THREAD

**Issue by Valerie-Freeman** [day-cohort-70/rare-api-sprint-stars-team-3#43]
As a reader, I would like to see the content of a Post so I can read it.

**Given** a user is viewing a list of Posts  
**When** they select a post to read  
**Then** they should be directed to a Post Detail page that shows the Post Details.

Post Details include:

* Title
* Header image (if exists)
* Content
* Publication date (MM/DD/YYYY)
* Author's Display Name

**Comment by DannyJamesHidalgo** [comment]
1

**Comment by samsheps** [comment]
This will be a GET request within the API:
- create a post module 
- SM will build out this module, push it to the branch, and Garrett will build out further functionality on the post module (add a tag, create a post, view all)
