### ISSUE TITLE
View Current User's Posts-ask steve for clarification 2 Or 3

### ISSUE THREAD

**Issue by Valerie-Freeman** [day-cohort-70/rare-api-sprint-stars-team-3#44]
As an author, I would like to see a list of all the Posts I have written so that I can easily view, edit, delete, publish or unpublish them.

**Given** the user is in the Rare application  
**When** they select the `My Posts` menu option  
**Then** they should be directed to the "My Posts" list page  
**And** the page should display ALL the Posts authored by the logged-in user  
**And** each post in the list should display the title, author and category  
**And** the list should be in order of creation date with the most recent on top

**Comment by DannyJamesHidalgo** [comment]
2 or 3. ask steve for clarification

**Comment by DannyJamesHidalgo** [comment]
need to update posts table to include a n boolean for publish

**Comment by DannyJamesHidalgo** [comment]
-API-

create a Posts module to define our methods for interacting with the sql database- 
for the time being only build a simple get_all_posts(). 

import the method into __init__.py and then import from views into json-server.py
