### ISSUE TITLE
Logout-2

### ISSUE THREAD

**Issue by Valerie-Freeman** [day-cohort-70/rare-api-sprint-stars-team-3#45]
As a user I would like to be able to logout of the system so that I can ensure that no one else who uses my computer will have access to my Rare account.

**Given** an authenticated user is in the Rare application  
**When** they select the `Logout` option from the menu  
**Then** they should be logged out of the system  
**And** they should be directed to the home page

**Comment by DannyJamesHidalgo** [comment]
2-

**Comment by DannyJamesHidalgo** [comment]
this is a front end client side ticket. open up client side to debug and get showing on the page.

**Comment by samsheps** [comment]
This appears to be already built out on client side; just need to double-check workability.

**Comment by reison-admin** [comment]
Completed with issue #46, works as intended.
